### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by toyatch** [toyatch/.emacs.d#1]
メモ

for Windows
- [ ] 2023/04/23 windows上でGitBashを介さずに起動したとき、git fetchなどのSSH接続ができない問題を解消したい
- [ ]  2023/04/23 shell-modeでgit logしたときに結果が最後まで流れるのではなく１画面で止めたい(less)
- [ ] 2023/06/02 日本語ファイル名のファイルをprettierで変換したい(コマンド直接実行した場合eshell NG, shell OK)
